import { FormatDefinition } from './types';

export const FORMATS: FormatDefinition[] = [
  {
    id: 'mp4',
    label: 'MP4 (H.264 / AAC)',
    ext: 'mp4',
    kind: 'video',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    extraArgs: ['-pix_fmt', 'yuv420p'],
    mimeTypes: ['video/mp4'],
  },
  {
    id: 'webm',
    label: 'WebM (VP9 / Opus)',
    ext: 'webm',
    kind: 'video',
    videoCodec: 'libvpx-vp9',
    audioCodec: 'libopus',
    mimeTypes: ['video/webm'],
  },
  {
    id: 'mov',
    label: 'MOV (H.264 / AAC)',
    ext: 'mov',
    kind: 'video',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    extraArgs: ['-pix_fmt', 'yuv420p'],
    mimeTypes: ['video/quicktime'],
  },
  {
    id: 'avi',
    label: 'AVI (MPEG-4 / MP3)',
    ext: 'avi',
    kind: 'video',
    videoCodec: 'mpeg4',
    audioCodec: 'libmp3lame',
    mimeTypes: ['video/x-msvideo'],
  },
  {
    id: 'mp3',
    label: 'MP3',
    ext: 'mp3',
    kind: 'audio',
    audioCodec: 'libmp3lame',
    mimeTypes: ['audio/mpeg'],
  },
  {
    id: 'wav',
    label: 'WAV (PCM 16-bit)',
    ext: 'wav',
    kind: 'audio',
    audioCodec: 'pcm_s16le',
    mimeTypes: ['audio/wav', 'audio/x-wav'],
  },
  {
    id: 'flac',
    label: 'FLAC',
    ext: 'flac',
    kind: 'audio',
    audioCodec: 'flac',
    mimeTypes: ['audio/flac', 'audio/x-flac'],
  },
  {
    id: 'm4a',
    label: 'M4A / AAC',
    ext: 'm4a',
    kind: 'audio',
    audioCodec: 'aac',
    mimeTypes: ['audio/mp4', 'audio/aac'],
  },
  {
    id: 'mkv',
    label: 'MKV (H.264 / AAC)',
    ext: 'mkv',
    kind: 'video',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    extraArgs: ['-pix_fmt', 'yuv420p'],
    mimeTypes: ['video/x-matroska'],
  },
  {
    id: 'flv',
    label: 'FLV (H.264 / AAC)',
    ext: 'flv',
    kind: 'video',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    extraArgs: ['-pix_fmt', 'yuv420p', '-ar', '44100'],
    mimeTypes: ['video/x-flv'],
  },
  {
    id: 'wmv',
    label: 'WMV',
    ext: 'wmv',
    kind: 'video',
    videoCodec: 'wmv2',
    audioCodec: 'wmav2',
    mimeTypes: ['video/x-ms-wmv'],
  },
  {
    id: 'ts',
    label: 'MPEG-TS (H.264 / AAC)',
    ext: 'ts',
    kind: 'video',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    extraArgs: ['-pix_fmt', 'yuv420p'],
    mimeTypes: ['video/mp2t'],
  },
  {
    id: '3gp',
    label: '3GP (H.264 / AAC)',
    ext: '3gp',
    kind: 'video',
    videoCodec: 'libx264',
    audioCodec: 'aac',
    extraArgs: ['-profile:v', 'baseline', '-level', '3.0', '-pix_fmt', 'yuv420p'],
    mimeTypes: ['video/3gpp'],
  },
  {
    id: 'ogv',
    label: 'OGV (Theora / Vorbis)',
    ext: 'ogv',
    kind: 'video',
    videoCodec: 'libtheora',
    audioCodec: 'libvorbis',
    mimeTypes: ['video/ogg'],
  },
  {
    id: 'gif',
    label: 'GIF 動圖',
    ext: 'gif',
    kind: 'video',
    extraArgs: ['-an', '-loop', '0'],
    mimeTypes: ['image/gif'],
  },
  {
    id: 'ogg',
    label: 'OGG (Vorbis)',
    ext: 'ogg',
    kind: 'audio',
    audioCodec: 'libvorbis',
    mimeTypes: ['audio/ogg'],
  },
  {
    id: 'opus',
    label: 'Opus',
    ext: 'opus',
    kind: 'audio',
    audioCodec: 'libopus',
    mimeTypes: ['audio/opus'],
  },
  {
    id: 'wma',
    label: 'WMA',
    ext: 'wma',
    kind: 'audio',
    audioCodec: 'wmav2',
    mimeTypes: ['audio/x-ms-wma'],
  },
  {
    id: 'aiff',
    label: 'AIFF (PCM 16-bit)',
    ext: 'aiff',
    kind: 'audio',
    audioCodec: 'pcm_s16be',
    mimeTypes: ['audio/aiff', 'audio/x-aiff'],
  },
  {
    id: 'jpg',
    label: 'JPEG',
    ext: 'jpg',
    kind: 'image',
    mimeTypes: ['image/jpeg'],
  },
  {
    id: 'png',
    label: 'PNG',
    ext: 'png',
    kind: 'image',
    mimeTypes: ['image/png'],
  },
  {
    id: 'webp',
    label: 'WebP',
    ext: 'webp',
    kind: 'image',
    mimeTypes: ['image/webp'],
  },
  {
    id: 'tiff',
    label: 'TIFF',
    ext: 'tiff',
    kind: 'image',
    mimeTypes: ['image/tiff'],
  },
  {
    id: 'avif',
    label: 'AVIF',
    ext: 'avif',
    kind: 'image',
    mimeTypes: ['image/avif'],
  },
];

export function getFormatById(id: string): FormatDefinition | undefined {
  return FORMATS.find((format) => format.id === id);
}
